### ISSUE TITLE
HTML runner check mark doesn't display correctly.

### ISSUE THREAD

**Issue by blittle** [busterjs/buster#301]
The buster-test.css contains the rule:

``` css

.buster-test .success h3:before {
    color: #3c3;
    content: "✓";
    padding-right: 6px;
}

```

But the content tag doesn't always translate correctly. It should probably be the actual character code:

`content: '\002713';`
